Repository saberland/saber, pull requests merged in 2019-08, with the labels that each got.

#259 feat: Add saber eject-theme command
  packages/saber/lib/cli-commands/build.js
  packages/saber/lib/cli-commands/dev.js
  packages/saber/lib/cli-commands/eject-theme.js
  packages/saber/lib/cli-commands/index.js
  packages/saber/lib/cli-commands/serve.js
  packages/saber/lib/cli-commands/utils.js
  packages/saber/lib/cli.js
  packages/saber/package.json
  website/pages/docs/themes.md
  yarn.lock
Labels: in review

#362 fix scoped package support
  packages/saber/lib/utils/__test__/resolvePackage.test.js
  packages/saber/lib/utils/resolvePackage.js
Labels: bug

#366 feat: add saber-plugin-search
  packages/saber-plugin-search/README.md
Labels: type: feature
